export interface Property {
  id: string
  price: number
  address: string
  suburb: string
  state: string
  postcode: string
  propertyType: string
  landSize: number
  buildingArea: number
  bedrooms: number
  bathrooms: number
  carSpaces: number
  facilities: string[]
  yearBuilt: number
  energyRating: string
  maintenanceCostAnnual: number
  estimatedRentalValueWeekly: number
  medianPrice: number
  agentName: string
  agency: string
  nearbySchools: number
  nearbyTransport: number
}

export const dummyProperties: Property[] = [
  {
    id: "1",
    price: 725000,
    address: "42 Crown Street",
    suburb: "Surry Hills",
    state: "NSW",
    postcode: "2010",
    propertyType: "Apartment",
    landSize: 150,
    buildingArea: 95,
    bedrooms: 2,
    bathrooms: 1,
    carSpaces: 1,
    facilities: ["Swimming Pool", "Gym", "Concierge"],
    yearBuilt: 2015,
    energyRating: "5 Star",
    maintenanceCostAnnual: 4500,
    estimatedRentalValueWeekly: 550,
    medianPrice: 750000,
    agentName: "Emma Johnson",
    agency: "Elite Properties",
    nearbySchools: 0.8,
    nearbyTransport: 0.3,
  },
  {
    id: "2",
    price: 580000,
    address: "88 Victoria Road",
    suburb: "Parramatta",
    state: "NSW",
    postcode: "2150",
    propertyType: "House",
    landSize: 520,
    buildingArea: 180,
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    facilities: ["Backyard", "Garage"],
    yearBuilt: 2008,
    energyRating: "4 Star",
    maintenanceCostAnnual: 3200,
    estimatedRentalValueWeekly: 450,
    medianPrice: 600000,
    agentName: "Michael Chen",
    agency: "Premier Homes",
    nearbySchools: 1.2,
    nearbyTransport: 0.5,
  },
  {
    id: "3",
    price: 950000,
    address: "156 Smith Street",
    suburb: "Collingwood",
    state: "VIC",
    postcode: "3066",
    propertyType: "Townhouse",
    landSize: 180,
    buildingArea: 160,
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    facilities: ["Balcony", "Air Conditioning"],
    yearBuilt: 2018,
    energyRating: "6 Star",
    maintenanceCostAnnual: 2800,
    estimatedRentalValueWeekly: 580,
    medianPrice: 920000,
    agentName: "Sarah Wilson",
    agency: "Urban Living",
    nearbySchools: 0.9,
    nearbyTransport: 0.2,
  },
  {
    id: "4",
    price: 520000,
    address: "234 Main Road",
    suburb: "Southbank",
    state: "VIC",
    postcode: "3006",
    propertyType: "Apartment",
    landSize: 120,
    buildingArea: 85,
    bedrooms: 2,
    bathrooms: 1,
    carSpaces: 1,
    facilities: ["River View", "Gym", "Security"],
    yearBuilt: 2016,
    energyRating: "5 Star",
    maintenanceCostAnnual: 3800,
    estimatedRentalValueWeekly: 480,
    medianPrice: 530000,
    agentName: "David Brown",
    agency: "City Properties",
    nearbySchools: 0.6,
    nearbyTransport: 0.1,
  },
  {
    id: "5",
    price: 675000,
    address: "567 Wickham Street",
    suburb: "Fortitude Valley",
    state: "QLD",
    postcode: "4006",
    propertyType: "Apartment",
    landSize: 140,
    buildingArea: 110,
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 1,
    facilities: ["Balcony", "Pool", "Gym"],
    yearBuilt: 2017,
    energyRating: "5 Star",
    maintenanceCostAnnual: 4000,
    estimatedRentalValueWeekly: 520,
    medianPrice: 680000,
    agentName: "Lisa Anderson",
    agency: "Queensland Realty",
    nearbySchools: 1.1,
    nearbyTransport: 0.4,
  },
  {
    id: "6",
    price: 620000,
    address: "789 Toorak Road",
    suburb: "Malvern",
    state: "VIC",
    postcode: "3144",
    propertyType: "House",
    landSize: 680,
    buildingArea: 220,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    facilities: ["Pool", "Garage", "Backyard"],
    yearBuilt: 2010,
    energyRating: "4 Star",
    maintenanceCostAnnual: 3600,
    estimatedRentalValueWeekly: 520,
    medianPrice: 630000,
    agentName: "James Mitchell",
    agency: "Prestige Properties",
    nearbySchools: 0.7,
    nearbyTransport: 0.8,
  },
  {
    id: "7",
    price: 495000,
    address: "123 Oxford Street",
    suburb: "Paddington",
    state: "NSW",
    postcode: "2021",
    propertyType: "Apartment",
    landSize: 100,
    buildingArea: 75,
    bedrooms: 1,
    bathrooms: 1,
    carSpaces: 0,
    facilities: ["Rooftop Terrace", "Concierge"],
    yearBuilt: 2014,
    energyRating: "4 Star",
    maintenanceCostAnnual: 3200,
    estimatedRentalValueWeekly: 420,
    medianPrice: 510000,
    agentName: "Nicole Taylor",
    agency: "Inner Sydney Homes",
    nearbySchools: 0.5,
    nearbyTransport: 0.2,
  },
  {
    id: "8",
    price: 850000,
    address: "456 Park Avenue",
    suburb: "Carina",
    state: "QLD",
    postcode: "4152",
    propertyType: "House",
    landSize: 750,
    buildingArea: 250,
    bedrooms: 4,
    bathrooms: 3,
    carSpaces: 2,
    facilities: ["Pool", "Garden", "Deck"],
    yearBuilt: 2012,
    energyRating: "4 Star",
    maintenanceCostAnnual: 4200,
    estimatedRentalValueWeekly: 580,
    medianPrice: 860000,
    agentName: "Robert Garcia",
    agency: "Brisbane Living",
    nearbySchools: 0.9,
    nearbyTransport: 1.2,
  },
]
